### ISSUE TITLE
SDK doesn't restore already connected session data

### ISSUE THREAD

**Issue by bigman212** [MetaMask/metamask-android-sdk#48]
## Steps to reproduce in sample app:
1) Open app and connect Metamask wallet using SDK
2) Close app
3) Open app

## Expected result
The SDK uses the previous session with a public key and other stuff without need to call `connect`.

## Actual result
You need to call `connect` and redirect to Metamask wallet every time you want to use SDK.

@elefantel @andreahaku

**Comment by elefantel** [comment]
Hi @bigman212 , there's currently a bug we are aware of that subsequent connections should not require a connection prompt on the wallet but should automatically reconnect. 

However, we do not store keys on device, so it is necessary to reconnect. Storing key presupposes that the wallet instance is still running (which may not be the case) and that the wallet also stores the keys - which it does not. The SDK does persist the session id so that subsequent reconnections are more seamless.

**Comment by bigman212** [comment]
I see. 
Then I think we can close this issue.
I didn't know that an app needs to call `connect` every time it needs some action from Metamask. Maybe we can add this info in the readme

**Comment by christopherferreira9** [comment]
Hi @bigman212 ! We have an ongoing bug issue in the mobile side that should fix this. We'll keep you posted once it has been merged. You can follow it [here](https://github.com/MetaMask/metamask-mobile/issues/7525).

**Comment by christopherferreira9** [comment]
Hi @bigman212 we're going to close this issue, please refere to the [mobile issue](https://github.com/MetaMask/metamask-mobile/issues/7525) to check its status.
